<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Jude-Tacwel" failures="1" tests="6" name="Test" time="43.075" errors="0" timestamp="2023-07-17T15:44:27 EDT">
  <testcase classname="com.naveenAutomation.FrameworkDemo.YourStoreTest" name="ValidateLogin" time="0.768"/>
  <testcase classname="com.naveenAutomation.FrameworkDemo.AccountLoginTest" name="testfailure" time="0.013">
    <skipped/>
  </testcase> <!-- testfailure -->
  <testcase classname="com.naveenAutomation.FrameworkDemo.AccountLoginTest" name="testfailure" time="0.005">
    <skipped/>
  </testcase> <!-- testfailure -->
  <testcase classname="com.naveenAutomation.FrameworkDemo.AccountLoginTest" name="testfailure" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [JudeT] but found [Jude]">
      <![CDATA[java.lang.AssertionError: expected [JudeT] but found [Jude]
at com.naveenAutomation.FrameworkDemo.AccountLoginTest.testfailure(AccountLoginTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testfailure -->
  <testcase classname="com.naveenAutomation.FrameworkDemo.AccountLoginTest" name="validateLoginUsingInvalidVredentials" time="2.436"/>
  <testcase classname="com.naveenAutomation.FrameworkDemo.AccountLoginTest" name="validateLoginUsingValidCredentials" time="3.086"/>
</testsuite> <!-- Test -->
